name: donate_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0" 

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.2
  provider: ^6.0.5
  badges: ^3.1.1
  firebase_core: ^3.11.0
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  sqflite: ^2.4.1              
  sqflite_common_ffi: ^2.3.3      
  sqflite_common_ffi_web: ^0.4.4   
  path: ^1.9.0
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.4.0
  file_picker: ^8.3.2
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
